[settings]
  verbose = true
  debug = true
  strict = true
  build_dir = "dist/"
  site_dir = "site/"
  default_template_file = "templates/base.html"
  default_content_selector = "main"
  default_content_action = "append_child"
  index_page = "index"
  page_file_extensions = ["html", "org"]
  doctype = "<!DOCTYPE html>"
  plugin_discovery = true
  plugin_dirs = ["plugins"]
  pretty_print_html = false

[custom_options]
  post_summary_max_entries = 10
  atom_feeds = false
  site_url = "https://drollery.org"
  site_author = "Ian Shepard Pringle"
  site_author_email = "hello@drollery.org"
  site_title = "Drollery"
  site_subtitle = "Life in the margins"
  site_logo = "https://drollery.org/favicon.svg"

[preprocessors]
  #md = 'scripts/markdown.mjs'
  org = 'pandoc -f org -t html'

[widgets.insert-generator-meta]
  widget = "generator-meta"

[widgets.set-page-title]
  widget = "title"
  selector = "h1"
  default = "Ian's World"
  append = " &mdash; Drollery.org"
  
[widgets.insert-header]
  widget = "include"
  selector = "main"
  action = "insert_before"
  file = "templates/header.html"

[widgets.insert-footer]
  widget = "include"
  selector = "body"
  action = "append_child"
  file = "templates/footer.html"
