[settings]
  verbose = true
  debug = true
  strict = true
  build_dir = "dist/"
  site_dir = "site/"
  default_template_file = "templates/base.html"
  default_content_selector = "main"
  default_content_action = "append_child"
  index_page = "index"
  page_file_extensions = ["html", "md"]
  doctype = "<!DOCTYPE html>"
  plugin_discovery = true
  plugin_dirs = ["plugins"]

[custom_options]
  blog_summary_max_entries = 10
  atom_feeds = false
  site_url = "https://ian.ist"
  site_author = "Ian Shepard Pringle"
  site_author_email = "hello@ian.ist"
  site_title = "ian.ist"
  site_subtitle = "Ian's World"
  site_logo = "https://ian.ist/favicon.svg"

[preprocessors]
  md = 'scripts/markdown.sh'

[index]
  index = true
  section = "blog/"
  sort_descending = true
  extract_after_widgets = ['insert-reading-time', 'make-post-header']
  sort_by = "date"
  leaf_file = ".leaf"

[index.fields]
  title = { selector = ["#post-title", "h1"] }
  excerpt = { selector = ["#post-excerpt", "p"] }
  date = { selector = ["#post-date", "time"] }
  tags = { selector = ".post-tag", select_all = true }
  reading_time = { selector = "#reading-time" }

[index.views.blog-index]
  index_selector = "#blog-entries"
  section = "blog"
  index_template = """
    {% for e in entries %}
    <h2><a href="{{e.url}}">{{e.title}}</a></h2>
    <div><strong>Last update:</strong> {{e.date}}</div>
    {% if e.tags %}
    <div class="post-tags">
       <strong>Tags: </strong>
       {%- for t in e.tags -%}
         <a href="/blog/tag/{{t}}"><span class="post-tag">{{t}}</span></a>{% if not loop.last %}, {% endif %}
       {%- endfor -%}
    </div>
    {% endif %}
    <div><strong>Reading time:</strong> {{e.reading_time}}</div>
    <p>{{e.excerpt}}</p>
    <a href="{{e.url}}">Read more</a>
    {% endfor %}
  """
  file = "helpers/blog-index.lua"

[index.views.blog-summary]
  index_selector = "#latest-blog-entries"
  section = "blog"
  index_template = """
    {% set limit = int(soupault_config.custom_options.blog_summary_max_entries) %}
    <dl>
      {% for e in sublist(0, limit, entries) %}
      <dt>{{e.date}}</dt>
      <dd> <a href="{{e.url}}">{{e.title}}</a> </dd>
      {% endfor %}
      </ul>
    </dl>
  """

#[widgets.inline-normalize-css]
#  widget = "inline-normalize-css"

[widgets.insert-generator-meta]
  widget = "generator-meta"

[widgets.set-page-title]
  widget = "title"
  selector = ["#page-title", "h1"]
  default = "Ian's World"
  append = " &mdash; ian.ist"

[widgets.insert-header]
  widget = "include"
  selector = "main"
  action = "insert_before"
  file = "templates/header.html"

[widgets.highlight-active-link]
  widget = "section-link-highlight"
  after = ["insert-header"]
  selector = "nav"
  active_link_class = "nav-active"

[widgets.insert-footer]
  widget = "include"
  selector = "body"
  action = "append_child"
  file = "templates/footer.html"

[widgets.make-post-header]
  widget = "post-header"
  section = "blog/"
  exclude_page = "blog/index.md"
  content_container_selector = "main"
  post_header_template = '''
    <div id="post-header">
      <h1 id="post-title">{{title}}</h1>
      <div><strong>Last update:</strong> <time id="post-date" datetime="{{date}}">{{date}}</time></div>
      {% if tags %}
        <div class="post-tags">
         <span><strong>Tags:</strong> </span>
         {%- for t in tags -%}
           <a href="/blog/tag/{{t}}"><span class="post-tag">{{t}}</span></a>{% if not loop.last %}, {% endif %}
         {%- endfor -%}
         </div>
        {% endif %}
    </div>
'''

[widgets.insert-reading-time-container]
  widget = "insert_html"
  after = "make-post-header"
  section = "blog/"
  exclude_path_regex = "(.*)/index(.*)"
  action = "append_child"
  selector = "#post-header"
  html = '<div><strong>Reading time:</strong> <span id="reading-time"></span></div>'

[widgets.insert-reading-time]
  widget = "reading-time"
  after = "insert-reading-time-container"
  selector = "#reading-time"
  content_selector = "main"

[widgets.atom]
  widget = "atom"
  page = "blog/index.md"
  feed_file = "atom.xml"
  use_section = "blog"