#+title: Dr Horner Plan

Dr Horner's Bible Reading Plan divides the books of the Bible into ten groups.
These groups are of various lengths and each day you read the next chapter in
each of the ten groups, meaning everyday you read ten chapters. When you have
read all the books in a given section it rolls-over to the start and the next
day you'll read the first chapter in the first book of that specific section.

To solve this problem just takes a little math. Written out, if the day number
is less than the total number of chapters in the section, just find
~total-chapters~ modulo ~day-number~. Otherwise, we flip the numbers and find
~day-number~ modulo ~total-chapters~. Either way it will leave us with the chapter
we should be on currently.

Set the book lists. First the Gospel readings:
#+begin_src elisp
(setq books-1 '(("Matthew" 28)
                ("Mark" 16)
                ("Luke" 24)
                ("John" 21)))
#+end_src

#+begin_src elisp
(defun get-reading (day books)
  (let ((chapter day))
    (while books
      (let ((book (pop books)))
      (if (> (nth 1 book) chapter)
        (message "%s %d" (nth 0 book) chapter)
        (progn
          (setq chapter (- chapter (nth 1 book))
                books (append books (book))))))))
#+end_src

