:PROPERTIES:
:AUTHOR: Ian S. Pringle
:CREATED: <2022-08-22 Mon>
:MODIFIED: <2022-08-26 Fri 14:25>
:TYPE: note
:END:
#+title: Recipes

* Inbox
* Baking
** Breads
*** No-Knead Cheese Burger Buns
:PROPERTIES:
:source-url: https://www.kingarthurbaking.com/recipes/no-knead-cheese-burger-buns-recipe
:servings: [6 6 buns]
:prep-time: 10 minutes
:cook-time: 21 minutes
:ready-in: 2 hours, 29 minutes
:END:
**** Ingredients
- 2 3/4 cups (330g) King Arthur Unbleached All-Purpose Flour
- 1/3 cup (35g) [product-link]Better Cheddar Cheese Powder[/product-link] or 1/2 cup (57g) finely grated sharp cheddar or Parmesan cheese
- 3/4 teaspoon salt*
- 1 teaspoon onion powder optional but tasty
- 1 tablespoon granulated sugar
- 2 1/2 teaspoons instant yeast
- 4 tablespoons (57g) butter softened
- 1 large egg
- 2/3 to 3/4 cup (152g to 170g) lukewarm water**
- 2 tablespoons (28g) butter melted
**** Directions
1. Weigh your flour; or measure it by gently spooning it into a cup, then
   sweeping off any excess. Combine all of the ingredients, and beat at high
   speed, using an electric mixer, for 2 minutes. To use your bread machine, put
   everything in the bucket, and let the dough go through its dough or manual
   cycle; skip to step 3 below if you're using a bread machine.,
2. Place the dough in a lightly greased bowl or rising bucket, cover it, and let
   it rise for 60 to 90 minutes, until it's noticeably puffy.,
3. Gently deflate the dough, and divide it into 6 pieces; each will be about
   111g, a scant 4 ounces.,
4. Shape the dough into balls, and place them in the wells of a lightly greased
   hamburger bun pan. If you don't have a bun pan, space them on a lightly
   greased or parchment-lined baking sheet.,
5. Gently flatten the buns with your hand to fill the bottom of the pan's wells,
   or until they're about 3 1/2" to 4" wide.,
6. Cover the buns, and let them rise for 60 to 90 minutes, until they're
   noticeably puffy. Towards the end of the rising time, preheat the oven to
   350°F.,
7. Brush each bun with some of the melted butter.,
8. Bake the buns for 16 to 19 minutes, until they're a light, golden brown, and
   their interior temperature is at least 190°F, measured with an instant-read
   thermometer.,
9. Remove the buns from the oven, transfer them to a rack, and brush with the
   remaining melted butter. Allow the buns to cool completely, then store
   airtight at room temperature.
** Desserts
*** My best Vanilla Cake
:PROPERTIES:
:source-url: https://www.recipetineats.com/my-very-best-vanilla-cake/
:servings: 10 - 12
:prep-time: 20 minutes
:cook-time: 30 minutes
:ready-in: 3 hours
:END:
**** Ingredients

- 2 cups all purpose flour (cake flour OK too, Note 1)
- 2 1/2 teaspoons baking powder (check it's still active, Note 2)
- 1/4 tsp salt
- 4 large eggs (50 – 55g / 2 oz each), at room temp (Note 3)
- 1 1/2 cups caster / superfine sugar (granulated/regular ok too, Note 2)
- 115g / 1/2 cup unsalted butter , cut into 1.5cm / 1/2” cubes (or so)
- 1 cup milk , full fat (Note 5)
- 3 tsp vanilla extract , the best you can afford (Note 6)
- 3 tsp vegetable or canola oil (Note 7)
- 225g / 2 sticks unsalted butter , softened
- 500g / 1 lb soft icing sugar / powdered sugar , SIFTED
- 3 tsp vanilla extract
- 2 – 4 tbsp milk , to adjust thickeness
**** Directions

1. Preheat oven to 180°C/350°F (160°C fan) for 20 minutes before starting the
   batter (Note 8). Place shelf in the middle of the oven.
2. Grease 2 x 20cm / 8” cake pans with butter, then line with parchment / baking
   paper. (Note 9 more pan sizes) Best to use cake pan without loose base, if
   you can.
3. Whisk flour, baking powder and salt in a large bowl. Set aside.
4. Beat eggs for 30 seconds on speed 6 of a Stand Mixer fitted with a whisk
   attachment, or hand beater.
5. With the beater still going, pour the sugar in over 45 seconds.
6. Then beat for 7 minutes on speed 8, or until tripled in volume and white.
7. Heat Milk-Butter:  While egg is beating, place butter and milk in a heatproof
   jug and microwave 2 minutes on high to melt butter (or use stove). Do not let
   milk bubble and boil (foam ok). Don’t do this ahead and let the milk cool
   (this affects rise).
8. Gently add flour:  When the egg is whipped, scatter 1/3 flour across surface,
   then beat on Speed 1 for 5 seconds. Add half remaining flour, then mix on
   Speed 1 for 5 sec. Add remaining flour, then mix on Speed 1 for 5 – 10 sec
   until the flour is just mixed in. Once you can’t see flour, stop straight
   away.
9. Lighten hot milk with some Egg Batter:  Pour hot milk, vanilla and oil into
   the now empty flour bowl. Add about 1 1/2 cups (2 ladles or so) of the Egg
   Batter into the Milk-Butter (don't need to be 100% accurate with amount). Use
   a whisk to mix until smooth – you can be vigorous here. Will look foamy.
10. Slowly add milk:  Turn beater back on Speed 1 then pour the Milk mixture
    into the Egg Batter over 15 seconds, then turn beater off.
11. Scrape and final mix:  Scrape down sides and base of bowl. Beat on Speed 1
    for 10 seconds – batter should now be smooth and pourable.
12. Pour batter into pans.
13. Knock out bubbles:  Bang each cake pan on the counter 3 times to knock out
    big bubbles (Note 10 for why)
14. Bake 30 minutes  or until golden and toothpick inserted into centre comes
    out clean.
15. Remove from oven. Cool in cake pans for 15 minutes, then gently turn out
    onto cooling racks. If using as layer cakes, cool upside down – slight dome
    will flatten perfectly. Level cake = neat layers.

**** Notes
1. Cake flour works just fine with this recipe, but butter and vanilla flavour,
   and crumb is ever so slightly better using plain  / all purpose flour. Also,
   cake flour makes the cake surface sweaty and sticky the next day.
2. Caster / superfine sugar are finer grains than regular / granulated sugar so
   it dissolves when whipped with the eggs. Granulated / regular sugar sometimes
   doesn’t fully dissolve which doesn’t affect the cake rise or texture but can
   leave some very brown sugar specks on the surface / sides. Not a big deal –
   just visual if serving undecorated.
3. Eggs – important to be at room temp as they fluff better when whipped which
   is key to the fluffy texture of this cake. Also, fresher eggs aerate better =
   better rise. Old eggs don’t fluff as well.
    - Quick way to warm up fridge cold eggs – place in a large bowl, cover with
      warm tap water (just warm, not hot), leave for 5 minutes. Wipe dry (to
      avoid residual water dripping into bowl), then use per recipe.
    - Large eggs –  50 – 55g / 2 oz per egg this is the industry standard of egg
      sizes sold as “large eggs” in Australia and the US. If your eggs are
      significantly larger or smaller in size, just weigh your eggs and use 200
      – 220g / 8 oz in total (including shell) or 180 – 200g / 7.3 oz in total
      excluding shell (this is useful if you need to use a partial egg to make
      up the total required weight. Just crack eggs, whisk THEN pour into a bowl
      to measure out what you need).
4. Baking powder – dead baking powder is a common problem with cake fails, even
   if not past the expiry date. Here’s how to check yours is still good.
Baking soda (bi-carb) won’t make the cake rise quite as well. If you have no
choice, then use 3/4 teaspoons of baking soda.
5. Milk – if you sub with lower fat milk then the texture of the crumb becomes a
   little less tender. Do not substitute with non-dairy milk, such as soy or
   almond milk.
6. Vanilla come in all sorts of qualities. I use Vanilla Extract. Better quality
   (more expensive) = better flavour, but I think vanilla bean paste is wasted
   in cakes.
7. Oil – just 3 teaspoons makes a noticeable difference to the tenderness of the
   crumb AND keeps the crumb moist for days.
8. Oven preheating – 30 minutes preheat is recommended to ensure no loss of heat
   when the oven door is opened. Never use the rapid heat function on your oven
   for baking, no matter how fancy your oven is!
9. Cake pans – the batter is quite thin so to ensure no leakage, best not to use
   a cake pan with a loose base or a springform pan. If that’s all you’ve got,
   then use butter to firmly fill the gap (this should be enough – I had no
   leakage when I did this) and for extra insurance, try to cut the paper for
   the base slightly larger so it goes slightly up the wall.
    - 2 x 20cm / 8″ cake pans- per base recipe above, bake 30 minutes
    - 3 x 20cm / 8″ cake pans – 23 minutes at temp per recipe. If they don’t all
      fit, put 2 on the middle shelf and one on shelf below. Take out top 2 at
      23 minutes, then move bottom one up and bake for further 2 minutes.
    - 2 x 23 cm / 9″ cake pans – 27 minutes
    - 3 x 23 cm / 9″ cake pans – 20 minutes
    - 2 x 15cm / 6″ cake pans – halve the recipe, I haven’t made this size yet
      but expect will be 25 – 27 min bake time.
    - 12 cup tube pan or bundt pan (grease & dust with flour) – bake 1 hour, but
      note cake will not be as fluffy as pictured and described
    - 23 x 33 cm / 13 x 9″ rectangle cake – 30 minutes
    Perfect golden sides and base can be achieved by greasing generously with
   butter then flour dusting base and sides. However, it’s not my base recipe
   because very occasionally, the base will stick a bit and some of the golden
   skin comes off. Safer to use paper!
10. Knock out big bubbles – banging cake pans on counter will knock out big air
    bubbles in the batter that causes unsightly bubble brown spots on the
    surface and irregular holes in the crumb. It does not burst the tiny bubbles
    that make the cake rise – they are too small to bang out!
11. Sweetness note – sweeter than Asian cakes, less sweet than typical Western
    butter cakes. Please do not reduce sugar – 1 1/2 cups is minimum required to
    make the eggs foamy enough to rise.
12. Different measures in different countries – tablespoon and cup sizes differ
    slightly from country to country. In most recipes, the difference is not
    enough to affect the outcome of the recipe, but for baking recipes, you do
    need to be careful.
    - This cake recipe has been specifically tested using both US and Australian
      cups (the two countries with the greatest size variance) and the cakes
      were exactly the same. So you can have confidence that this recipe can be
      used no matter which country you are in – only exception is Japan (cup
      sizes are considerably smaller (200ml) so please use weights provided).
For absolutely certainty, opt to use the weights provided (click Metric toggle
button above ingredients). Professional kitchens only use weights.
13. Storage – if not frosting immediately once cooled, cover surface with baking
    paper (so it doesn’t stick to cling wrap) then wrap in cling wrap
    immediately then place in an airtight container. Do not leave it sitting
    around for hours once cooled, cakes go stale quite quickly. Leave out rather
    than in fridge, unless it’s super hot where you live. Keeps in freezer for 3
    months.
    - Frosted or wrapped unfrosted cake keeps perfectly for 4 days (as in,
      practically like freshly made). Still good on Day 7 but a bit less moist.
      Keeps better if frosted because it seals the moisture in. If frosted with
      buttercream, it can stay out on counter and is better stored this way
      unless it’s hot where you are (in which case refrigerate but take out of
      fridge a good hour before serving. Nobody likes cold buttercream frosting
      or cake!) Avoid pre slicing – the area most prone to drying cake out is
      the cut sides.
14. Frosting – If it becomes too sloppy/soft because the butter was too soft or
    your kitchen is too warm eg Aussie summer (!), just refrigerate 10 minutes –
    remove paddle attachment and stick it in the bowl – then whip again to
    re-fluff.
15. Nutrition per slice, assuming 10 servings. Cake only.
*** White Chocolate Frosting Recipe
:PROPERTIES:
:source-url: https://chelsweets.com/white-chocolate-frosting-recipe/
:servings: 7
:prep-time: 10 minutes
:cook-time: N/A
:ready-in: 10 minutes
:END:
**** Ingredients
- 1/4 cup heavy cream or whipping cream (60ml)
- 1 cup white chocolate chips  (175g)
- 2 cups unsalted butter, room temperature (434g; 1 lb. box)
- 1 Tbsp vanilla extract (12ml)
- 1/2 tsp salt (3g)
- 7 cups powdered sugar (907g; 2 lb. bag)
**** Directions

1. Place the heavy cream and white chocolate chips into a  heatproof bowl. Heat
   in the microwave on a high power for 1 minute.
2. Let the white chocolate / heavy cream mixture sit for 1 minute to allow the
   heat from the bowl to continue to melt the white chocolate chips.
3. Stir until smooth, then set aside to cool for about 10 minutes. If you have
   any bits of chocolate left unmelted, heat in additional 10 second increments
   and stir until the mixture is smooth.
4. In the bowl of a stand mixer or a separate large bowl, beat the room
   temperature butter on a low speed for 30 seconds with a paddle attachment or
   hand mixer until smooth.
5. Add in the vanilla extract and salt. Beat on low until combined.
6. Pour in the cooled white chocolate and heavy cream mixture, and mix on a low
   speed.
7. Slowly add in the powdered sugar, 1 cup at a time.
8. Scrape down the sides and bottom of the bowl with a rubber spatula as needed.
9. Mix on a low speed until the ingredients are fully incorporated and the
   desired consistency is reached. 
10. If the frosting is too thick, add in additional cream, 1 teaspoon at a time.
    If the frosting is too thin, add in more powdered sugar, a quarter of a cup
    at a time.
11. Stir by hand with a rubber spatula to make the frosting extra smooth at the
    end, then cover with plastic wrap and set aside until you're ready to use
    it!

* Cooking
** Breakfasts
** Main Courses
** Sides
** Desserts
* Drinks
