:PROPERTIES:
:AUTHOR: Ian S. Pringle
:CREATED: <2023-01-20 Fri>
:MODIFIED: <2023-04-26 Wed 13:50>
:TYPE: blog
:END:
#+title: Astro Has Failed Again
#+filetags: :meta:astrojs:
Just an annoyance with Astro, figuring out paths. I’m not exactly sure who is to blame, but I am blaming Astro anyway :)

What’s wrong? Right now my pathing requires that I specify the stuff between the root and the specific page/file, ie `foo.tld/things/i/specify/file-1-2-3`. I came up with a way to fix this and it works locally but deploying to GitHub and resulted in the Actions’ invoking of `yarn build` failing. I even had the idea of giving up on GitHub Actions, but that’s not really what I want.

Life was easier with Orgmode and NextJS! I would go right back to NextJS but I am really interested in using Neocities (I paid for it!) and that means static sites only.

I also tried building the _entire_ Obsidian vault I have and that resulted in memory issues and node.js crashed. So at some level I know that Astro is not going to work in the long term. Probably should keep poking at other options I guess.
