:PROPERTIES:
:AUTHOR: Ian S. Pringle
:CREATED: <2022-08-09 Tue>
:MODIFIED: <2022-08-24 Wed 10:54>
:TYPE: blog
:ID:       03a73675-93f5-4741-acf0-90b4623ab88b
:END:
#+title: Indie Web
#+filetags: :meta:web:

The [[https://indieweb.org][Indie Web]] is basically an attempt at providing standards and tooling to
create websites that are federated and connected to one another. Some of the
things they have include /IndieAuth/, /Webmentions/, /h-cards/, /h-entries/, and
syndication with /POSSE/. Almost all of these things are just standards that you
can implement on your site, like the /h-*/ stuff, and allow for other sites and
tools to interact with your own website. Some neat things that this allows for
are mostly automatic "webmentions", which are anything from comments on a post,
to response posts, and "shares". An /h-card/ is basically a business card that
other sites can find in your ~<head>~.

Anywho, I had this implemented before on my 0x44.pw website and I am going to
try to really implement the entire catalog of IndieWeb features here on /this/
site in Sylvan. Why? I think it's a cool exercise and allows for some neat
interactions.
