:PROPERTIES:
:AUTHOR: Ian S. Pringle
:CREATED: <2022-09-06 Tue 16:40>
:MODIFIED: <2022-09-06 Tue 16:46>
:TYPE: blog
:END:
#+title: Maybe Easy Is Better
#+filetags: :meta:

I have two major shortcomings that I am working to resolve with orgmode's
default org-publish:
 1. attachments do not work out of the gate
 2. it doesn't get me closer to the ox-huge workflow of one =blog.org= file

I have looked at some other potential options for my blog. NextJS is fine, I
like it even, but I worked on refactoring to Chakra-UI and it's annoying that it
still isn't really working right. The problem currently is that this other
package I need called =Prose= has it's own default theme settings and so
everything is wonky. I guess I can get that working, but... I don't know. I
looked at the orgmode default export and it's not bad. With a little CSS love
it's actually pretty good looking! There are some hacks I could use to make it
better. Some people are doing some pretty cool and crazy stuff with their
org-publish.
