#!/usr/bin/env node
const { src, dest, series } = require('gulp');
const htmlMinify = require('html-minifier');

const options = {
  minifyCSS: true,
  minifyJS: true,
  minifyURLs: true,
  includeAutoGeneratedTags: true,
  removeAttributeQuotes: true,
  removeComments: true,
  removeRedundantAttributes: true,
  removeScriptTypeAttributes: true,
  removeStyleLinkTypeAttributes: true,
  sortClassName: true,
  useShortDoctype: true,
  collapseWhitespace: true
};
src('dist/**/*.html') 
  .on('data', function(file) {
    const buferFile = Buffer.from(htmlMinify.minify(file.contents.toString(), options))
    return file.contents = buferFile
  })
  .pipe(dest('minified'))